language: java
jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov

before_install:
  - rm -rf /home/travis/.npm/*
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.4.deb

after_success:
  - codecov

services:
  - elasticsearch
  - rabbitmq
